// Formation templates with player positions as percentages
export interface FormationTemplate {
  name: string
  code: string
  description: string
  positions: Array<{
    positionCode: string
    x: number // 0-1 percentage from left
    y: number // 0-1 percentage from bottom (defensive end)
  }>
}

export const FORMATIONS: FormationTemplate[] = [
  {
    name: '4-4-2',
    code: '4-4-2',
    description: 'Classic balanced formation with two strikers',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LB', x: 0.1, y: 0.25 },
      { positionCode: 'LCB', x: 0.35, y: 0.2 },
      { positionCode: 'RCB', x: 0.65, y: 0.2 },
      { positionCode: 'RB', x: 0.9, y: 0.25 },
      { positionCode: 'LM', x: 0.1, y: 0.5 },
      { positionCode: 'LCM', x: 0.35, y: 0.45 },
      { positionCode: 'RCM', x: 0.65, y: 0.45 },
      { positionCode: 'RM', x: 0.9, y: 0.5 },
      { positionCode: 'LST', x: 0.35, y: 0.78 },
      { positionCode: 'RST', x: 0.65, y: 0.78 },
    ],
  },
  {
    name: '4-3-3',
    code: '4-3-3',
    description: 'Attacking formation with three forwards',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LB', x: 0.1, y: 0.25 },
      { positionCode: 'LCB', x: 0.35, y: 0.2 },
      { positionCode: 'RCB', x: 0.65, y: 0.2 },
      { positionCode: 'RB', x: 0.9, y: 0.25 },
      { positionCode: 'LCM', x: 0.3, y: 0.45 },
      { positionCode: 'CDM', x: 0.5, y: 0.38 },
      { positionCode: 'RCM', x: 0.7, y: 0.45 },
      { positionCode: 'LW', x: 0.15, y: 0.72 },
      { positionCode: 'ST', x: 0.5, y: 0.82 },
      { positionCode: 'RW', x: 0.85, y: 0.72 },
    ],
  },
  {
    name: '4-2-3-1',
    code: '4-2-3-1',
    description: 'Modern formation with double pivot',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LB', x: 0.1, y: 0.25 },
      { positionCode: 'LCB', x: 0.35, y: 0.2 },
      { positionCode: 'RCB', x: 0.65, y: 0.2 },
      { positionCode: 'RB', x: 0.9, y: 0.25 },
      { positionCode: 'LDM', x: 0.38, y: 0.38 },
      { positionCode: 'RDM', x: 0.62, y: 0.38 },
      { positionCode: 'LW', x: 0.15, y: 0.58 },
      { positionCode: 'CAM', x: 0.5, y: 0.58 },
      { positionCode: 'RW', x: 0.85, y: 0.58 },
      { positionCode: 'ST', x: 0.5, y: 0.8 },
    ],
  },
  {
    name: '3-5-2',
    code: '3-5-2',
    description: 'Wing-backs provide width with three center backs',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LCB', x: 0.25, y: 0.2 },
      { positionCode: 'CB', x: 0.5, y: 0.18 },
      { positionCode: 'RCB', x: 0.75, y: 0.2 },
      { positionCode: 'LWB', x: 0.08, y: 0.45 },
      { positionCode: 'LCM', x: 0.32, y: 0.42 },
      { positionCode: 'CDM', x: 0.5, y: 0.38 },
      { positionCode: 'RCM', x: 0.68, y: 0.42 },
      { positionCode: 'RWB', x: 0.92, y: 0.45 },
      { positionCode: 'LST', x: 0.38, y: 0.75 },
      { positionCode: 'RST', x: 0.62, y: 0.75 },
    ],
  },
  {
    name: '5-3-2',
    code: '5-3-2',
    description: 'Defensive formation with five at the back',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LWB', x: 0.08, y: 0.28 },
      { positionCode: 'LCB', x: 0.28, y: 0.2 },
      { positionCode: 'CB', x: 0.5, y: 0.18 },
      { positionCode: 'RCB', x: 0.72, y: 0.2 },
      { positionCode: 'RWB', x: 0.92, y: 0.28 },
      { positionCode: 'LCM', x: 0.32, y: 0.45 },
      { positionCode: 'CM', x: 0.5, y: 0.42 },
      { positionCode: 'RCM', x: 0.68, y: 0.45 },
      { positionCode: 'LST', x: 0.38, y: 0.75 },
      { positionCode: 'RST', x: 0.62, y: 0.75 },
    ],
  },
  {
    name: '4-1-4-1',
    code: '4-1-4-1',
    description: 'Lone striker with single holding midfielder',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LB', x: 0.1, y: 0.25 },
      { positionCode: 'LCB', x: 0.35, y: 0.2 },
      { positionCode: 'RCB', x: 0.65, y: 0.2 },
      { positionCode: 'RB', x: 0.9, y: 0.25 },
      { positionCode: 'CDM', x: 0.5, y: 0.35 },
      { positionCode: 'LM', x: 0.1, y: 0.52 },
      { positionCode: 'LCM', x: 0.35, y: 0.5 },
      { positionCode: 'RCM', x: 0.65, y: 0.5 },
      { positionCode: 'RM', x: 0.9, y: 0.52 },
      { positionCode: 'ST', x: 0.5, y: 0.8 },
    ],
  },
  {
    name: '3-4-3',
    code: '3-4-3',
    description: 'Aggressive attacking formation',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LCB', x: 0.25, y: 0.2 },
      { positionCode: 'CB', x: 0.5, y: 0.18 },
      { positionCode: 'RCB', x: 0.75, y: 0.2 },
      { positionCode: 'LWB', x: 0.08, y: 0.45 },
      { positionCode: 'LCM', x: 0.35, y: 0.42 },
      { positionCode: 'RCM', x: 0.65, y: 0.42 },
      { positionCode: 'RWB', x: 0.92, y: 0.45 },
      { positionCode: 'LW', x: 0.2, y: 0.72 },
      { positionCode: 'ST', x: 0.5, y: 0.8 },
      { positionCode: 'RW', x: 0.8, y: 0.72 },
    ],
  },
  {
    name: '4-5-1',
    code: '4-5-1',
    description: 'Defensive midfield-heavy formation',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LB', x: 0.1, y: 0.25 },
      { positionCode: 'LCB', x: 0.35, y: 0.2 },
      { positionCode: 'RCB', x: 0.65, y: 0.2 },
      { positionCode: 'RB', x: 0.9, y: 0.25 },
      { positionCode: 'LM', x: 0.1, y: 0.5 },
      { positionCode: 'LCM', x: 0.3, y: 0.45 },
      { positionCode: 'CM', x: 0.5, y: 0.42 },
      { positionCode: 'RCM', x: 0.7, y: 0.45 },
      { positionCode: 'RM', x: 0.9, y: 0.5 },
      { positionCode: 'ST', x: 0.5, y: 0.8 },
    ],
  },
  {
    name: '4-4-1-1',
    code: '4-4-1-1',
    description: 'Classic formation with a second striker behind',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LB', x: 0.1, y: 0.25 },
      { positionCode: 'LCB', x: 0.35, y: 0.2 },
      { positionCode: 'RCB', x: 0.65, y: 0.2 },
      { positionCode: 'RB', x: 0.9, y: 0.25 },
      { positionCode: 'LM', x: 0.1, y: 0.48 },
      { positionCode: 'LCM', x: 0.35, y: 0.42 },
      { positionCode: 'RCM', x: 0.65, y: 0.42 },
      { positionCode: 'RM', x: 0.9, y: 0.48 },
      { positionCode: 'CAM', x: 0.5, y: 0.62 },
      { positionCode: 'ST', x: 0.5, y: 0.8 },
    ],
  },
  {
    name: '5-4-1',
    code: '5-4-1',
    description: 'Ultra-defensive with five defenders',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LWB', x: 0.08, y: 0.28 },
      { positionCode: 'LCB', x: 0.28, y: 0.2 },
      { positionCode: 'CB', x: 0.5, y: 0.18 },
      { positionCode: 'RCB', x: 0.72, y: 0.2 },
      { positionCode: 'RWB', x: 0.92, y: 0.28 },
      { positionCode: 'LM', x: 0.15, y: 0.48 },
      { positionCode: 'LCM', x: 0.38, y: 0.45 },
      { positionCode: 'RCM', x: 0.62, y: 0.45 },
      { positionCode: 'RM', x: 0.85, y: 0.48 },
      { positionCode: 'ST', x: 0.5, y: 0.78 },
    ],
  },
  {
    name: '4-3-2-1',
    code: '4-3-2-1',
    description: 'Christmas tree formation',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LB', x: 0.1, y: 0.25 },
      { positionCode: 'LCB', x: 0.35, y: 0.2 },
      { positionCode: 'RCB', x: 0.65, y: 0.2 },
      { positionCode: 'RB', x: 0.9, y: 0.25 },
      { positionCode: 'LCM', x: 0.3, y: 0.4 },
      { positionCode: 'CM', x: 0.5, y: 0.38 },
      { positionCode: 'RCM', x: 0.7, y: 0.4 },
      { positionCode: 'LAM', x: 0.35, y: 0.58 },
      { positionCode: 'RAM', x: 0.65, y: 0.58 },
      { positionCode: 'ST', x: 0.5, y: 0.8 },
    ],
  },
  {
    name: '4-1-2-1-2',
    code: '4-1-2-1-2',
    description: 'Narrow diamond formation',
    positions: [
      { positionCode: 'GK', x: 0.5, y: 0.05 },
      { positionCode: 'LB', x: 0.1, y: 0.25 },
      { positionCode: 'LCB', x: 0.35, y: 0.2 },
      { positionCode: 'RCB', x: 0.65, y: 0.2 },
      { positionCode: 'RB', x: 0.9, y: 0.25 },
      { positionCode: 'CDM', x: 0.5, y: 0.35 },
      { positionCode: 'LCM', x: 0.32, y: 0.48 },
      { positionCode: 'RCM', x: 0.68, y: 0.48 },
      { positionCode: 'CAM', x: 0.5, y: 0.6 },
      { positionCode: 'LST', x: 0.38, y: 0.78 },
      { positionCode: 'RST', x: 0.62, y: 0.78 },
    ],
  },
]

// Get formation by code
export function getFormationByCode(code: string): FormationTemplate | undefined {
  return FORMATIONS.find((f) => f.code === code)
}
